// O5 disconnected fixtures. These are backend read-model examples, not a
// priority engine. main.js must not import this file during O4.

export const O5_HOME_FIXTURES = Object.freeze({
  only_input: {
    generated_at: '2026-08-12T08:00:00.000Z',
    now: null,
    needs_input: [{
      id: 'fu-goal-active',
      version: 3,
      kind: 'STATE_REVALIDATION',
      domain: 'Personal',
      need: '¿Sigue activo el objetivo de renovar la documentación?',
      reason: 'La respuesta desbloquea la siguiente acción',
      evidence: { goal_id: 'goal-docs', last_signal_at: '2026-06-01' },
      answer_schema: {
        type: 'SINGLE_CHOICE',
        options: ['ACTIVE', 'PAUSED', 'ABANDONED'],
      },
      priority_basis: ['Desbloquea una acción ejecutable', 'Importancia high'],
      blocking: true,
    }],
    attention: [],
    later: [],
    recent_changes: [],
    goal_progress: [],
    empty_state: null,
    sections: [{ kind: 'NEEDS_INPUT', item_ids: ['fu-goal-active'] }],
  },

  urgent_action: {
    generated_at: '2026-08-12T08:00:00.000Z',
    now: {
      id: 'action-elearning',
      title: 'Completar e-learning de seguridad',
      domain: 'VistaJet',
      reason: 'La obligación vence hoy',
      evidence: { due_date: '2026-08-12', obligation: true },
      linked_goal: { id: 'goal-compliance', title: 'Mantener compliance', status: 'ACTIVE' },
      status: 'ACCEPTED',
      priority_basis: ['Se puede ejecutar ahora', 'Urgencia now'],
    },
    needs_input: [],
    attention: [],
    later: [],
    recent_changes: [],
    goal_progress: [],
    empty_state: null,
    sections: [{ kind: 'NOW', item_id: 'action-elearning' }],
  },

  empty: {
    generated_at: '2026-08-12T08:00:00.000Z',
    now: null,
    needs_input: [],
    attention: [],
    later: [],
    recent_changes: [],
    goal_progress: [],
    empty_state: {
      title: 'Nada necesita tu atención ahora',
      reason: 'No hay acciones ejecutables, preguntas elegibles ni excepciones activas.',
    },
    sections: [],
  },

  full: {
    generated_at: '2026-08-12T08:00:00.000Z',
    now: {
      id: 'action-hr',
      title: 'Enviar documentación a HR',
      domain: 'Personal',
      reason: 'Desbloquea una revisión externa',
      evidence: { document_ready: true },
      linked_goal: { id: 'goal-hr', title: 'Cerrar trámite HR', status: 'ACTIVE' },
      status: 'ACCEPTED',
      priority_basis: ['Se puede ejecutar ahora'],
    },
    needs_input: [{
      id: 'fu-sleep',
      version: 1,
      kind: 'INFORMATION_REQUEST',
      domain: 'Salud',
      need: '¿Cuánto dormiste?',
      reason: 'Actualiza la energía disponible',
      evidence: { date: '2026-08-12' },
      answer_schema: { type: 'DURATION_MINUTES' },
      priority_basis: ['Nunca se ha preguntado'],
      blocking: false,
    }],
    attention: [{
      id: 'wait-provider',
      type: 'WAITING_FOR_OVERDUE',
      severity: 'TIME_SENSITIVE',
      title: 'Respuesta del proveedor',
      domain: 'JETMI',
      reason: 'La ventana de espera o escalación ha vencido',
      evidence: { waiting_on: 'Proveedor', escalation_at: '2026-08-11T08:00:00Z' },
    }],
    later: [{
      id: 'action-gym',
      title: 'Entrenar fuerza',
      domain: 'Gym',
      reason: 'Siguiente sesión semanal',
      evidence: { sessions_remaining: 1 },
      linked_goal: null,
      status: 'PROPOSED',
      priority_basis: ['Se puede ejecutar ahora'],
    }],
    recent_changes: [{
      id: 'change-goal-hr',
      category: 'GOAL_CHANGE',
      what_changed: 'El trámite de HR quedó pendiente de documentación',
      occurred_at: '2026-08-12T07:30:00.000Z',
      source: 'USER_REPORTED',
      impacted_area: 'Personal',
      consequence: 'Enviar la documentación pasa a ser la siguiente acción',
    }],
    goal_progress: [{
      id: 'goal-hr',
      title: 'Cerrar trámite HR',
      status: 'ACTIVE',
      progress: 0.5,
      progress_summary: 'Documentación preparada; falta enviarla',
      reason: null,
      evidence: { document_ready: true },
      updated_at: '2026-08-12T07:30:00.000Z',
    }],
    empty_state: null,
    sections: [
      { kind: 'NOW', item_id: 'action-hr' },
      { kind: 'NEEDS_INPUT', item_ids: ['fu-sleep'] },
      { kind: 'ATTENTION', item_ids: ['wait-provider'] },
      { kind: 'LATER', item_ids: ['action-gym'] },
      { kind: 'RECENT_CHANGES', item_ids: ['change-goal-hr'] },
      { kind: 'GOAL_PROGRESS', item_ids: ['goal-hr'] },
    ],
  },
});
